- project:
    check:
      jobs:
        - linters
    gate:
      jobs:
        - linters
    kebechet-auto-gate:
      jobs:
        - linters
    release:
      jobs:
        - upload-pypi-sesheta